### ISSUE TITLE
Errors Out During Make

### ISSUE THREAD

**Issue by lonnietc** [phip1611/diplomarbeit-impl#4]
Hello,

I was really want to build this code to see what wonderful work has been done, but it seems to Error Out during the "make" process even after all of the initial checks. (Please See Attached File)

[Errors_out01.txt](https://github.com/phip1611/diplomarbeit-impl/files/9174973/Errors_out01.txt)

Can you Please help?

The Error part:

```
    Checking x86_64 v0.14.10
    Checking elf_rs v0.2.0
    Checking uart_16550 v0.2.18
error: `ptr::mut_ptr::<impl *mut T>::add` is not yet stable as a const fn
  --> /home/lonnie/.cargo/registry/src/github.com-1ecc6299db9ec823/uart_16550-0.2.18/src/mmio.rs:28:36
   |
28 |             int_en: AtomicPtr::new(base_pointer.add(1)),
   |                                    ^^^^^^^^^^^^^^^^^^^
   |
   = help: add `#![feature(const_ptr_offset)]` to the crate attributes to enable

error: `ptr::mut_ptr::<impl *mut T>::add` is not yet stable as a const fn
  --> /home/lonnie/.cargo/registry/src/github.com-1ecc6299db9ec823/uart_16550-0.2.18/src/mmio.rs:29:39
   |
29 |             fifo_ctrl: AtomicPtr::new(base_pointer.add(2)),
   |                                       ^^^^^^^^^^^^^^^^^^^
   |
   = help: add `#![feature(const_ptr_offset)]` to the crate attributes to enable

error: `ptr::mut_ptr::<impl *mut T>::add` is not yet stable as a const fn
  --> /home/lonnie/.cargo/registry/src/github.com-1ecc6299db9ec823/uart_16550-0.2.18/src/mmio.rs:30:39
   |
30 |             line_ctrl: AtomicPtr::new(base_pointer.add(3)),
   |                                       ^^^^^^^^^^^^^^^^^^^
   |
   = help: add `#![feature(const_ptr_offset)]` to the crate attributes to enable

error: `ptr::mut_ptr::<impl *mut T>::add` is not yet stable as a const fn
  --> /home/lonnie/.cargo/registry/src/github.com-1ecc6299db9ec823/uart_16550-0.2.18/src/mmio.rs:31:40
   |
31 |             modem_ctrl: AtomicPtr::new(base_pointer.add(4)),
   |                                        ^^^^^^^^^^^^^^^^^^^
   |
   = help: add `#![feature(const_ptr_offset)]` to the crate attributes to enable

error: `ptr::mut_ptr::<impl *mut T>::add` is not yet stable as a const fn
  --> /home/lonnie/.cargo/registry/src/github.com-1ecc6299db9ec823/uart_16550-0.2.18/src/mmio.rs:32:38
   |
32 |             line_sts: AtomicPtr::new(base_pointer.add(5)),
   |                                      ^^^^^^^^^^^^^^^^^^^
   |
   = help: add `#![feature(const_ptr_offset)]` to the crate attributes to enable

error: could not compile `uart_16550` due to 5 previous errors
make[1]: *** [Makefile:2: runtime_environment] Error 1
make[1]: Leaving directory '/home/lonnie/Hedron/phip1611/test/diplomarbeit-impl/runtime-environment'
make: *** [Makefile:46: runtime_environment] Error 1

```

**Comment by phip1611** [comment]
Hi @lonnietc 
~~Hm, that is strange. Are you using Rust and Cargo installed through Rustup? You need a Rust toolchain that matches the version specified inside `rust-toolchain.toml`. If you use Rustup, it will be installed by default. Looks to me like you used a compiler version that is too old.~~

Edit: I can reproduce. There were breaking changes in the [uart_16550](https://github.com/rust-osdev/uart_16550/pull/22/files) crate that came in through a minor update.. I'm fixing it.

**Comment by phip1611** [comment]
Should be fixed @lonnietc

**Comment by lonnietc** [comment]
Hello,

I'm going to give it a try and will report back. Thanks

**Comment by lonnietc** [comment]
@phip1611 

success !!!

Looks like everything built this time. Awesome!!

**Comment by lonnietc** [comment]
@phip1611 Hello

Now it looks like I have an old QEMU installed

QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.23)

Your scripts seem to suggest that I need QEMU 6.2 or newer so I will have to install a new one.

Any word on how to build up an ISO so that I can boot on bare metal?

**Comment by phip1611** [comment]
> Any word on how to build up an ISO so that I can boot on bare metal?

I'll look into it. Not sure right now how to solve this.

> Your scripts seem to suggest that I need QEMU 6.2 or newer so I will have to install a new one.

Yeah, otherwise, startup may take some time (20+ sec). I recommend to use qemu 6.2 (or newer) either by using [the nix package manager](https://nixos.org/download.html) or by compiling it from source on your machine

For example, with the latest `<nixpkgs>`, you get qemu 7.0. Just open a shell with `nix-shell -p qemu`
