### ISSUE TITLE
Need FSGSBASE-capable CPU

### ISSUE THREAD

**Issue by lonnietc** [phip1611/diplomarbeit-impl#5]
Hello,

I was able to compile and run the code via SSH into one node of a "Dell PowerEdge C6220 SFF 4 Node Server 8x Xeon E5-2650 256GB RAM 4x 2TB 2.5" HD system" and got a message back from QEMU which seemed to hang from that point.

```
diplomarbeit-impl$ make run_nogui

Hedron Microhypervisor (Cyberus-7f934bf RELEASE x86_64): gcc 9.4.0 [MB1]

Need FSGSBASE-capable CPU
```

Does this mean that QEMU cannot emulate the FSGBASE capabilities?

**Comment by phip1611** [comment]
This is a limitation of Hedron and QEMU is to my best knowledge not capable
of emulating this feature (among other modern x86 features).
Your hardware seems to be quite old. Do you have access to a newer machine?

**Comment by lonnietc** [comment]
Yea, my 2 test systems are:

    Intel NUC (NUC7i7DNHE)
    Dell PowerEdge C6220 SFF 4 Node Server 8x Xeon E5-2650 256GB RAM 4x 2TB 2.5" HD system

On one of them (1) I have Windows 11 and on the second system (2) for which I have Ubuntu 20.04

Is this something special with Hedron as I do not recall having any issue when I booted an old version of NOVA (i.e. v0.3 Demo from NUL) some time ago?

**Comment by phip1611** [comment]
> Is this something special with Hedron

https://github.com/cyberus-technology/hedron#supported-platforms

The traditional NOVA doesn't use those features. I think new versions do so as well. At least XSAVE.

From Hedrons README:
*Recommended Intel CPUs are Intel Core processors starting with the **Ivy Bridge** microarchitecture.*

Your Intel E5-2650 is already quite old. Please use newer hardware when working with Hedron.
